[package]
name = "adduce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
optional_struct = "0.2.0"
toml = "0.5.10"
pulldown-cmark = "0.9.2"

