
# stylesheets are imported per file, pages support multiple css files
style = ["config/global/style.css"]

head = ["config/global/head.html"]
# main holds the body of the document in main there are blocks which have properties
[main]

# text can be hardcoded in blocks
[[main.block]]
style = "h1"
text = "Adduce"


[[main.block]]
style = "h3"
text = "Valence & ToastXC"


# markdown can be imported from files
[[main.block]]
from_str = "config/index/about.md"
style = "md"