
style = "config/style.css"

# main is the main div for the element
# support for multiple divs will be added in time
[main]

# blocks contain words and a style
[[main.block]]
text = "Adduce"
style = "h1"


[[main.block]]
text = "#### Valence & ToastXC"
style = "md"

[[main.block]]
from_str = "config/text.md"
style = "md"


[[main.block]]
style = "br"

