# template info
title = "Business Update"
locale = "AWST"
author = "Toast fox"


# blocks
[main]

# blocks contain words and a style
[[main.block]]
content = "Hello"
style = "h4"

[[main.block]]
content = "world"
style = "h5"

# custom html
# the html style will tell the compiler to ignore styling
[[main.block]]
content = "<h2>im html!</h2>"
style = "html"

# breaklines do not require content
[[main.block]]
style = "br"


[[main.block]]
# content will default to PLACEHOLER
# style will default to <p>

# html can also be imported from other files!
[[main.block]]
from_str = "text.html"
style = "html"